---
permalink: java/exceptions/gdvgwaz
title: Java program to demonstrate the use of nested try, catch, and finally blocks
---

<div class="codecard">Java program to demonstrate the use of nested try and catch blocks</div>
<div class="card">{{ site.javafile }}</div>
<pre class="code">{%- highlight java -%}
class GD
{
    public static void main(String args[])
    {
        String s=null;
        int n=515, d=0, result=0;
        try
        {
            try
            {
                result=n/d;
            }
            catch(ArithmeticException e)
            {
                System.out.println("Exception caught in the first nested catch block");
            }
            System.out.println("Length: "+s.length());
        }
        catch(ArithmeticException e)
        {
            System.out.println("Exception caught in the first catch block");
        }
        catch(Exception e)
        {
            System.out.println("Exception caught in the third catch block");
        }
    }
}
{%- endhighlight -%}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runjava }}
Exception caught in the first nested catch block
Exception caught in the third catch block
godarda@gd:~$ 
</pre></span>

<div class="codecard">Java program to demonstrate the use of nested try and catch blocks</div>
<div class="card">{{ site.javafile }}</div>
<pre class="code">{%- highlight java -%}
class GD
{
    public static void main(String args[])
    {
        String s=null;
        int n=515, d=0, result=0;
        try
        {
            System.out.println("Length: "+s.length());
        }
        catch(ArithmeticException e)
        {
            System.out.println("Exception caught in the first catch block");
        }
        catch(Exception e1)
        {
            try
            {
                result=n/d;
            }
            catch(ArithmeticException e2)
            {
                System.out.println("Exception caught in the first nested catch block");
            }
            System.out.println("Exception caught in the third catch block");
        }
    }
}
{%- endhighlight -%}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runjava }}
Exception caught in the first nested catch block
Exception caught in the third catch block
godarda@gd:~$ 
</pre></span>

<div class="codecard">{{ page.title }}</div>
<div class="card">{{ site.javafile }}</div>
<pre class="code">{%- highlight java -%}
class GD
{
    public static void main(String args[])
    {
        String s=null;
        int n=515, d=0, result=0;
        try
        {
            System.out.println("Length: "+s.length());
        }
        catch(ArithmeticException e)
        {
            System.out.println("Exception caught in the first catch block");
        }
        catch(Exception e1)
        {
            try
            {
                result=n/d;
            }
            catch(ArithmeticException e2)
            {
                System.out.println("Exception caught in the first nested catch block");
            }
            finally
            {
                System.out.println("Finally block will always execute");
            }
            System.out.println("Exception caught in the third catch block");
        }
        finally
        {
            System.out.println("Finally block will always execute");
        }
    }
}
{%- endhighlight -%}</pre>
<div class="card">{{ site.output }}</div>
<span><pre>
{{ site.runjava }}
Exception caught in the first nested catch block
Finally block will always execute
Exception caught in the third catch block
Finally block will always execute
godarda@gd:~$ 
</pre></span>